language: node_js
node_js:
  - "10"
directories:
  - node_modules
script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - npm run build
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
before_deploy:
  - git tag "$(date +'%Y%m%d-%H%M%S')-$(git log --format=%h -1)"
#deploy:
#  - provider: releases
#    api_key: $GITHUB_TOKEN
#    file_glob: true
#    file: bundle.tar.gz
#    on:
#      branch: master
#      repo: Artsdatabanken/nin-kart-frontend
#    skip_cleanup: true
# Trigge på nytt
after_success:
  #  - npm run report-coverage
  - ls -la ..
  - ./deploy.sh $BRANCH
  - ./deploy_django.sh $BRANCH
  - curl -X POST --data-urlencode "payload={\"channel\": \"$slack_chan\", \"username\": \"travis not the band\", \"text\": \"$slack_command\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/$SLACK_TOKEN
  - curl -X POST --data-urlencode "payload={\"channel\": \"$slack_chan\", \"username\": \"travis not the band\", \"text\": \"$slack_command2\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/$SLACK_TOKEN
notifications:
  slack:
    on_success: change
    on_failure: change
before_install:
  - sudo apt-get install -y sshpass
