language: node_js
node_js:
  - "10"
directories:
  - node_modules
script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - npm run build
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - cd wms-assistent
  - npm install
  - npm run build
  - cd ..

after_success:
  - ./deploy.sh $BRANCH
  - ./deploy_wms-assistent.sh $BRANCH
  - ./deploy_django.sh $BRANCH
notifications:
  slack:
    on_success: change
    on_failure: change
before_install:
  - sudo apt-get install -y sshpass
